### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by obayit** [ionic-team/native-run#129]
**Version:**

1.0.0

**Description:**

When I run `native-run android --list --json --verbose` I get an error.

```
  native-run Caught fatal error: /usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
  native-run       } catch {
  native-run               ^
  native-run 
  native-run SyntaxError: Unexpected token {
  native-run     at createScript (vm.js:80:10)
  native-run     at Object.runInThisContext (vm.js:139:10)
  native-run     at Module._compile (module.js:617:28)
  native-run     at Object.Module._extensions..js (module.js:664:10)
  native-run     at Module.load (module.js:566:32)
  native-run     at tryModuleLoad (module.js:506:12)
  native-run     at Function.Module._load (module.js:498:3)
  native-run     at Module.require (module.js:597:17)
  native-run     at require (internal/module.js:11:18)
  native-run     at Object.<anonymous> (/usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/index.js:3:44) +0ms
{
	"error": "/usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/make-dir.js:85\n      } catch {\n              ^\n\nSyntaxError: Unexpected token {\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/index.js:3:44)"

```

**SDK Info:**

~~Same error when i run `native-run android --sdk-info`~~
**Edit:** not the same error. `--sdk-info` gives:
```
/usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/native-run/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

To be honest, my android sdk installation might be wrong.
I installed it manually at first, then using `apt`, then copied files from manual installation to `/usr/lib/android-sdk`.
Nevertheless I thought you might want to fix this.

**Comment by dwieeb** [comment]
@obayit What Node version are you using?

**Comment by obayit** [comment]
@dwieeb `node --version` outputs `v8.16.2`
