### ISSUE TITLE
ADB deployment and --list option unhandled error

### ISSUE THREAD

**Issue by luciojb** [ionic-team/native-run#22]
Hi all.

Just today i updated my ionic cli to 5.0.0, but could not run on android anymore as it asked for native run Ok, installed it. No run either....

```
[ERROR] Error while getting native targets for android: No suitable API installation found.
        native-run needs a fully installed SDK Platform to run your app.
        - Run native-run android --sdk-info to see missing packages for each API level.
        - Install missing packages in Android Studio by opening the SDK manager.
        This error occurred while using native-run. You can try running this command with --no-native-run, which will
        revert to using Cordova.
```

Then i tried with the --no-native-run flag, and then it ran fine. I'm using ADB to connect my phone.

The problem is, as i'm trying to run without that ugly flag (no-native-run), and tried to list the connected devices. I got this output:

```
lucio@pop-os:~/holonfix/mechanicionic$ native-run --list
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: connect ENOENT /var/run/usbmuxd
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

```
My environment is as follows:

```
Ionic:

   Ionic CLI          : 5.0.0 (/home/lucio/.nvm/versions/node/v11.12.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, (and 18 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.1.1

System:

   Android SDK Tools : 26.1.1 (/home/lucio/Android/Sdk)
   NodeJS            : v11.12.0 (/home/lucio/.nvm/versions/node/v11.12.0/bin/node)
   npm               : 6.9.0
   OS                : Linux 4.18


```

If you could try to replicate the error and solve it, it would help a lot. Also, what do i need to do to run the app without the flag? Is there something i'm missing to configure or is it the ADB tool? If it's the tool, please, add the support. I hate to have one more cable in my desk, so i always use wireless to run my android app with ionic.

Please and thanks!

**Comment by dwieeb** [comment]
@luciojb What is the output of `native-run android --sdk-info --verbose` ?

**Comment by dwieeb** [comment]
I'm guessing you don't have a system image installed, which actually isn't an issue if you're only wanting to target hardware devices. So, I'll log this as a bug: https://github.com/ionic-team/native-run/issues/23

**Comment by dwieeb** [comment]
@luciojb The usbmuxd unhandled error is actually because the bare `--list` is trying to list iOS devices. We're working on a better solution for that, too.

You can list just Android devices with `native-run android --list`.

**Comment by dwieeb** [comment]
Can you elaborate on what you meant here?

> I hate to have one more cable in my desk, so i always use wireless to run my android app with ionic.

You still need a cable to deploy the app to your device, right? The same cable can be used to have your app connected to the dev server.

**Comment by luciojb** [comment]
> You still need a cable to deploy the app to your device, right? The same cable can be used to have your app connected to the dev server.

Using adb, actually you just connect the cable once to configure the tool. You run `adb tcpip <port>` and then `adb connect <android device's ip>:<port from previous step>`. Then, you can disconnect the cable and Ionic (ionic cordova run android, in previous versions) would deploy to the device configured with adb. Next time, say, tomorrow, i just run that second command (adb connect ...) and then the daemon will connect to my phone without cable.

Sometimes (device's system update or something), i have to redo the first command with the cable connected, but it's like once a month. 

> This is fixed in 0.1.2!

I updated to that version, but still can't deploy with ADB without using the flag. I'm updating everything (Android Studio, etc) to see if it fixes the problem, though i think it is related to this package here. 

> What is the output of native-run android --sdk-info --verbose ?

```
lucio@pop-os:~/holonfix/mechanicionic$ native-run android --sdk-info --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk +6ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android +1ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /home/lucio/Android/Sdk to discover SDK packages +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [ { apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-28', 'sources;android-28' ] },
  native-run:android:utils:sdk:api:getAPILevels   { apiLevel: '27', packages: [ 'platforms;android-27' ] } ] +0ms
SDK Location:         /home/lucio/Android/Sdk
AVD Home:             /home/lucio/.android/avd

API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Sources for Android 28  sources;android-28  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  /.+/


API Level:            27
Packages:             Android SDK Platform 27  platforms;android-27  3
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-27;google_apis_playstore;x86  /.+/


Tools:

Android Emulator  emulator  28.0.23
Android SDK Build-Tools 28.0.3  build-tools;28.0.3  28.0.3
Android SDK Platform-Tools  platform-tools  28.0.2
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1
```

So i don't know about that system image, isn't it for emulating? I'm not emulating, i'm using a real device... I'll do some research to see if that may be the problem, but it doesn't make sense, since it deploys with the --no-native-run flag...

**Comment by luciojb** [comment]
Hi again. Running a few commands, it seems there is something happening using this package and adb... Here i'll put some flow of commands running to understand this. I hope it'll be useful.
```

lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list
Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list
Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ adb devices
List of devices attached
192.168.0.3:5555	device

lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list
Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
lucio@pop-os:~/holonfix/mechanicionic$ adb devices
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully

lucio@pop-os:~/holonfix/mechanicionic$ adb devices
List of devices attached

lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ adb devices
List of devices attached
192.168.0.3:5555	device

lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list
Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
lucio@pop-os:~/holonfix/mechanicionic$ 

```

Sorry if this isn't very legible, but i'm not good with markdown, so i'm just using code. Also, i don't have the time right now to format it properly. :)

**Comment by dwieeb** [comment]
> Using adb, actually you just connect the cable once to configure the tool.

Cool, makes sense.

So it looks like native-run is breaking that connection? I'm not sure how that's possible. To list devices, we simply run `adb devices -l`. 

Can you run `native-run android --list --verbose`? Perhaps there's an error being hidden. It will at least reveal more.

**Comment by luciojb** [comment]
I'll put the result of the suggested commands to run below:
```

lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached
192.168.0.3:5555       device product:mido model:Redmi_Note_4 device:mido transport_id:1

lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk +3ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /home/lucio/Android/Sdk to discover SDK packages +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [ { apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-28', 'sources;android-28' ] },
  native-run:android:utils:sdk:api:getAPILevels   { apiLevel: '27', packages: [ 'platforms;android-27' ] } ] +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 28: Unsatisfied packages within API 28: system-images;android-28;google_apis_playstore;x86 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 27: Unsatisfied packages within API 27: system-images;android-27;google_apis_playstore;x86 +0ms
  native-run:android:utils:list:getVirtualTargets Error getting virtual targets: { Error: No suitable API installation found.
  native-run:android:utils:list:getVirtualTargets     at getDefaultAVDSchematic (/home/lucio/.nvm/versions/node/v11.12.0/lib/node_modules/native-run/dist/android/utils/avd.js:92:11)
  native-run:android:utils:list:getVirtualTargets   code: 'ERR_UNSUITABLE_API_INSTALLATION',
  native-run:android:utils:list:getVirtualTargets   exitCode: 1,
  native-run:android:utils:list:getVirtualTargets   data: undefined } +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [] +3s
Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully

lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached

lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached
192.168.0.3:5555       device product:mido model:Redmi_Note_4 device:mido transport_id:1

lucio@pop-os:~/holonfix/mechanicionic$ 

```

**Comment by luciojb** [comment]
Searching for this:

`  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 28: Unsatisfied packages within API 28: system-images;android-28;google_apis_playstore;x86 +0ms
`

I found [this gist](https://gist.github.com/mrk-han/66ac1a724456cadf1c93f4218c6060ae) and then ran:

```console
lucio@pop-os:~/Android/Sdk/tools/bin$ sdkmanager --install "system-images;android-28;google_apis;x86"
```

Fine, now the ionic command ran successfully.... In an emulator! He still cannot find my device through adb. Here are the new outputs of listing verbose:

```console
lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk +3ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd +1ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ '/home/lucio/.android/avd/Pixel_2_API_28.ini' ] +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /home/lucio/Android/Sdk to discover SDK packages +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/system-images/android-28/google_apis/x86/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [ { apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages:
  native-run:android:utils:sdk:api:getAPILevels      [ 'platforms;android-28',
  native-run:android:utils:sdk:api:getAPILevels        'system-images;android-28;google_apis;x86',
  native-run:android:utils:sdk:api:getAPILevels        'sources;android-28' ] },
  native-run:android:utils:sdk:api:getAPILevels   { apiLevel: '27', packages: [ 'platforms;android-27' ] } ] +0ms
  native-run:android:utils:avd:validateSkin Checking skin layout file: /home/lucio/Android/Sdk/skins/pixel_2/layout +0ms
  native-run:android:utils:avd:validateSystemImagePath Checking package.xml file: /home/lucio/Android/Sdk/system-images/android-28/google_apis/x86/package.xml +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Using schematic Pixel_2_API_28 for default AVD +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [] +3s
Connected Devices:

  No connected devices found

Virtual Devices:

  Pixel 2 API 28 (API 28) Pixel_2_API_28

```

**Comment by dwieeb** [comment]
@luciojb Yeah, the system image is only used for emulators. You can force native-run to use a device with `--device`, but there's a bug: it doesn't handle devices connected over tcp/ip. Just made this issue to track that: https://github.com/ionic-team/native-run/issues/30

**Comment by luciojb** [comment]
> @luciojb Yeah, the system image is only used for emulators. You can force native-run to use a device with `--device`, but there's a bug: it doesn't handle devices connected over tcp/ip. Just made this issue to track that: #30

Yeah, though so too. So i'll wait until the tcp/ip bug on --device is fixed. Thank you very much for following this issue! :)

**Comment by dwieeb** [comment]
@luciojb Thank you for being so responsive and patient! 

Could you try with a test release? `npm i -g native-run@0.2.2-testing.0`

I think there's still an underlying issue. With my testing, I was still able to get a device but it was wrong, whereas your output suggests it doesn't find the device at all (`native-run:android:utils:adb:getDevices Found adb devices: [] +3`)

If it still doesn't work with the testing release, please post the full output again with `--verbose`.

**Comment by luciojb** [comment]
Installed the testing version, even then the device isn't found. It runs in the emulator even with --device. So i'm posting the commands i ran with this testing version:

```console
lucio@pop-os:~/holonfix/mechanicionic$ adb connect 192.168.0.3:5555
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
connected to 192.168.0.3:5555
lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached
192.168.0.3:5555       device product:mido model:Redmi_Note_4 device:mido transport_id:1

lucio@pop-os:~/holonfix/mechanicionic$ native-run android --list --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk +4ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ '/home/lucio/.android/avd/Pixel_2_API_28.ini' ] +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /home/lucio/Android/Sdk to discover SDK packages +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/system-images/android-28/google_apis/x86/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/system-images/android-28/google_apis_playstore/x86/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [ { apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages:
  native-run:android:utils:sdk:api:getAPILevels      [ 'platforms;android-28',
  native-run:android:utils:sdk:api:getAPILevels        'system-images;android-28;google_apis;x86',
  native-run:android:utils:sdk:api:getAPILevels        'system-images;android-28;google_apis_playstore;x86',
  native-run:android:utils:sdk:api:getAPILevels        'sources;android-28' ] },
  native-run:android:utils:sdk:api:getAPILevels   { apiLevel: '27', packages: [ 'platforms;android-27' ] } ] +0ms
  native-run:android:utils:avd:validateSkin Checking skin layout file: /home/lucio/Android/Sdk/skins/pixel_2/layout +0ms
  native-run:android:utils:avd:validateSystemImagePath Checking package.xml file: /home/lucio/Android/Sdk/system-images/android-28/google_apis/x86/package.xml +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Using schematic Pixel_2_API_28 for default AVD +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [] +3s
Connected Devices:

  No connected devices found

Virtual Devices:

  Pixel 2 API 28 (API 28) Pixel_2_API_28
lucio@pop-os:~/holonfix/mechanicionic$ adb devices -l
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
lucio@pop-os:~/holonfix/mechanicionic$ 

```

**Comment by dwieeb** [comment]
Maybe this is related to this issue: `adb server version (41) doesn't match this client (39); killing...`

If the server/client connection keeps breaking, native-run can't get the list of devices...

**Comment by luciojb** [comment]
Well, this only happens when i run the native-run commands, explicitly or not - using ionic, it runs behind, it's not explicit but it's running, as you can see with my `ionic cordova run android --device --verbose`:

```console
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --verbose
2019-05-31T19:10:52.130Z native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME
2019-05-31T19:10:52.133Z native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk
2019-05-31T19:10:52.133Z native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME
2019-05-31T19:10:52.133Z native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android
2019-05-31T19:10:52.133Z native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME
2019-05-31T19:10:52.133Z native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd
2019-05-31T19:10:52.134Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml
2019-05-31T19:10:52.150Z native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ]
2019-05-31T19:10:52.156Z native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ]
2019-05-31T19:10:52.156Z native-run:android:utils:adb:getDevices Found adb devices: []
2019-05-31T19:10:52.157Z native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ '/home/lucio/.android/avd/Pixel_2_API_28.ini' ]
No hardare devices found, attempting emulator...
2019-05-31T19:10:52.160Z native-run:android:utils:sdk:findAllSDKPackages Walking /home/lucio/Android/Sdk to discover SDK packages
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/emulator/package.xml
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/tools/package.xml
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/build-tools/28.0.3/package.xml
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/patcher/v4/package.xml
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-27/package.xml
2019-05-31T19:10:52.180Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platforms/android-28/package.xml
2019-05-31T19:10:52.181Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/sources/android-28/package.xml
2019-05-31T19:10:52.181Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/system-images/android-28/google_apis/x86/package.xml
2019-05-31T19:10:52.181Z native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/system-images/android-28/google_apis_playstore/x86/package.xml
2019-05-31T19:10:52.214Z native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [ { apiLevel: '28',
    packages:
     [ 'platforms;android-28',
       'system-images;android-28;google_apis;x86',
       'system-images;android-28;google_apis_playstore;x86',
       'sources;android-28' ] },
  { apiLevel: '27', packages: [ 'platforms;android-27' ] } ]

```

It cannot find my device either, like in this lines:

```
2019-05-31T19:10:52.150Z native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ]
2019-05-31T19:10:52.156Z native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ]
2019-05-31T19:10:52.156Z native-run:android:utils:adb:getDevices Found adb devices: []
```

As you can see in the outputs in the other comments, i connect to the device, then run native-run commands and then check through the ADB tool if the device is still connected, but isn't anymore. The flow is exactly as i'm showing in the code, it's the copy of my terminal. 

It isn't with Ionic because even the native-run list commands cause the 

`adb server version (41) doesn't match this client (39); killing...`

I really don't understand much about this tool, so i can't contribute any other way but to send the result of the commands. It's not a major issue as i can run without this native-run, but if it's an Ionic default new way of running apps to devices, then I can do nothing but try to use it.

**Comment by luciojb** [comment]
[https://stackoverflow.com/questions/43050370/adb-server-version-36-doesnt-match-this-client-39-not-using-genymotion](https://stackoverflow.com/questions/43050370/adb-server-version-36-doesnt-match-this-client-39-not-using-genymotion)

Here, we have this thing: i installed adb through my ubuntu terminal. But the Android SDK also offers an adb tool within platform-tools folder. 

When i use adb in terminal, it used the one installed in `/usr/bin/adb`, but the native-run uses the platform-tools one, therefore, 

`adb server version (41) doesn't match this client (39); killing...`

Starting the adb client within the SDK/platform-tools and then running the native-run, it doesn't crash anymore and also runs my app on the device!

**Comment by dwieeb** [comment]
I was just going to ask for the output of `which adb`!

**Comment by dwieeb** [comment]
@luciojb Here are some docs on setting up your PATH to use binaries inside your installed SDK: https://ionicframework.com/docs/installation/android#configuring-command-line-tools

**Comment by dwieeb** [comment]
I am debating whether it makes sense for native-run to prefer a "global" adb or the one installed with the SDK. Generally it's better if the Android tools are all managed in the same place. Also, I believe Android Studio will prefer the tools inside the SDK as well.

**Comment by luciojb** [comment]
> I am debating whether it makes sense for native-run to prefer a "global" adb or the one installed with the SDK. Generally it's better if the Android tools are all managed in the same place. Also, I believe Android Studio will prefer the tools inside the SDK as well.

I think so too, but i don't know the impact over the people who are using the global one. Maybe show a message when trying to run or something like that, like "Make sure you are using the Android SDK provided ADB tool".

I updated my path to `export PATH=$PATH:$ANDROID_HOME/platform-tools` and removed the global one.

**Comment by dwieeb** [comment]
Awesome!

Made an issue for that: https://github.com/ionic-team/native-run/issues/31

**Comment by dwieeb** [comment]
@luciojb Can this be closed then? 😄

**Comment by luciojb** [comment]
Yes, can be closed! Thanks for your help!

**Comment by dwieeb** [comment]
Thanks again for your patience! 😄

**Comment by OlatunjiGab** [comment]
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 6s
Picked up _JAVA_OPTIONS: -Xmx512M
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --device
[native-run] Selected hardware device 039143394L047851
[native-run] Error: ENOENT: no such file or directory, open 'C:\Users\Gabriel\Documents\GabFile\MyProject\Bookstore1\platforms\android\app\build\outputs\apk\debug\app-debug.apk'
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by OlatunjiGab** [comment]
Any Help On this? This Project failed to build

**Comment by dwieeb** [comment]
@OlatunjiGab That is unrelated and looks like an Ionic CLI issue. Please create an issue here: https://github.com/ionic-team/ionic-cli
