### ISSUE TITLE
Android device over tcpip:5555 error: more than one device/emulator

### ISSUE THREAD

**Issue by shuhikari** [ionic-team/native-run#28]
When trying to run `ionic cordova run android --livereload` with a device over tcpip:5555 It won't find the correct device

```
> cordova build android
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --connect --forward 8100:8100
[native-run] No hardare devices found, attempting emulator...
[native-run] Selected emulator 192.168.0.7:5555
[native-run] Error: Command failed: /Users/shuhikari/Library/Android/sdk/platform-tools/adb -s 192.168.0.7:5555 reverse tcp:8100 tcp:8100
[native-run] adb: error: more than one device/emulator
[native-run] 
[native-run]     at ChildProcess.exithandler (child_process.js:294:12)
[native-run]     at ChildProcess.emit (events.js:189:13)
[native-run]     at maybeClose (internal/child_process.js:970:16)
[native-run]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess native-run.
        
        native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug...
        exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

**Comment by dwieeb** [comment]
The `more than one device/emulator` error usually occurs when the target is ambiguous, which is why native-run invokes `adb` with the serial flag (`adb -s 192.168.0.7:5555`). Not sure why this is happening. What's the output of `adb devices -l`?

**Comment by shuhikari** [comment]
@dwieeb  the output shows only the device connected

```
adb devices -l              
List of devices attached
192.168.0.7:5555       device product:karatep model:Lenovo_K53b36 device:K53b36 transport_id:1
```

**Comment by dwieeb** [comment]
What is the output of `native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --verbose` ?

**Comment by luciojb** [comment]
I'm back! Having the same issue. May be related in some way with #22, but maybe not. It is running fine without livereload. Here's the output with `ionic cordova run android --livereload --verbose`:

```console
[native-run] 2019-06-03T19:35:05.407Z native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ]
[native-run] 2019-06-03T19:35:05.413Z native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached',
[native-run]   '192.168.0.3:5555       device product:mido model:Redmi_Note_4 device:mido transport_id:1',
[native-run]   '',
[native-run]   '' ]
[native-run] 2019-06-03T19:35:05.414Z native-run:android:utils:adb:getDeviceProperties Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s', '192.168.0.3:5555', 'shell', 'getprop' ]
[native-run] 2019-06-03T19:35:05.484Z native-run:android:utils:adb:getDevices Found adb devices: [ { serial: '192.168.0.3:5555',
[native-run]     state: 'device',
[native-run]     type: 'hardware',
[native-run]     connection: 'tcpip',
[native-run]     properties:
[native-run]      { product: 'mido',
[native-run]        model: 'Redmi_Note_4',
[native-run]        device: 'mido',
[native-run]        transport_id: '1' },
[native-run]     manufacturer: 'Xiaomi',
[native-run]     model: 'Redmi Note 4',
[native-run]     product: 'mido',
[native-run]     sdkVersion: '24' } ]
[native-run] 2019-06-03T19:35:05.485Z native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ '/home/lucio/.android/avd/Pixel_2_API_28.ini' ]
[native-run] Selected hardware device 192.168.0.3:5555
[native-run] 2019-06-03T19:35:05.604Z native-run:android:utils:adb:getDeviceProperty Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s',
[native-run]   '192.168.0.3:5555',
[native-run]   'shell',
[native-run]   'getprop',
[native-run]   'dev.bootcomplete' ]
[native-run] 2019-06-03T19:35:05.655Z native-run:android:utils:adb:waitForBoot Device 192.168.0.3:5555 is booted!
[native-run] 2019-06-03T19:35:05.655Z native-run:android:utils:adb:forwardPorts Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s', '192.168.0.3:5555', 'reverse', 'tcp:8100', 'tcp:8100' ]
[native-run] 2019-06-03T19:35:05.664Z native-run Caught fatal error: { Error: Command failed: /home/lucio/Android/Sdk/platform-tools/adb -s 192.168.0.3:5555 reverse tcp:8100 tcp:8100
[native-run] adb: error: more than one device/emulator
[native-run] 
[native-run]     at ChildProcess.exithandler (child_process.js:297:12)
[native-run]     at ChildProcess.emit (events.js:197:13)
[native-run]     at maybeClose (internal/child_process.js:988:16)
[native-run]     at Socket.stream.socket.on (internal/child_process.js:404:11)
[native-run]     at Socket.emit (events.js:197:13)
[native-run]     at Pipe._handle.close (net.js:611:12)
[native-run]   killed: false,
[native-run]   code: 1,
[native-run]   signal: null,
[native-run]   cmd:
[native-run]    '/home/lucio/Android/Sdk/platform-tools/adb -s 192.168.0.3:5555 reverse tcp:8100 tcp:8100',
[native-run]   stdout: '',
[native-run]   stderr: 'adb: error: more than one device/emulator\n' }
[native-run] Error: Command failed: /home/lucio/Android/Sdk/platform-tools/adb -s 192.168.0.3:5555 reverse tcp:8100 tcp:8100
[native-run] adb: error: more than one device/emulator
[native-run] 
[native-run]     at ChildProcess.exithandler (child_process.js:297:12)
[native-run]     at ChildProcess.emit (events.js:197:13)
[native-run]     at maybeClose (internal/child_process.js:988:16)
[native-run]     at Socket.stream.socket.on (internal/child_process.js:404:11)
[native-run]     at Socket.emit (events.js:197:13)
[native-run]     at Pipe._handle.close (net.js:611:12)
[ERROR] An error occurred while running subprocess native-run.
        
        native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug... exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 5 functions +0ms
  ionic:lib:hooks Looking for ionic:serve:after npm script. +26s
  ionic:utils-process processExit: exiting (exit code: 1) +20ms

```

and here is the output with `native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --verbose`:

```console
lucio@pop-os:~/holonfix/mechanicionic$ native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at /home/lucio/Android/Sdk +3ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /home/lucio/.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /home/lucio/.android/avd +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /home/lucio/Android/Sdk/platform-tools/package.xml +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached',
  native-run:android:utils:adb:parseAdbDevices   '192.168.0.3:5555       device product:mido model:Redmi_Note_4 device:mido transport_id:1',
  native-run:android:utils:adb:parseAdbDevices   '',
  native-run:android:utils:adb:parseAdbDevices   '' ] +0ms
  native-run:android:utils:adb:getDeviceProperties Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s', '192.168.0.3:5555', 'shell', 'getprop' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [ { serial: '192.168.0.3:5555',
  native-run:android:utils:adb:getDevices     state: 'device',
  native-run:android:utils:adb:getDevices     type: 'hardware',
  native-run:android:utils:adb:getDevices     connection: 'tcpip',
  native-run:android:utils:adb:getDevices     properties:
  native-run:android:utils:adb:getDevices      { product: 'mido',
  native-run:android:utils:adb:getDevices        model: 'Redmi_Note_4',
  native-run:android:utils:adb:getDevices        device: 'mido',
  native-run:android:utils:adb:getDevices        transport_id: '1' },
  native-run:android:utils:adb:getDevices     manufacturer: 'Xiaomi',
  native-run:android:utils:adb:getDevices     model: 'Redmi Note 4',
  native-run:android:utils:adb:getDevices     product: 'mido',
  native-run:android:utils:adb:getDevices     sdkVersion: '24' } ] +85ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ '/home/lucio/.android/avd/Pixel_2_API_28.ini' ] +0ms
Selected hardware device 192.168.0.3:5555
  native-run:android:utils:adb:getDeviceProperty Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s',
  native-run:android:utils:adb:getDeviceProperty   '192.168.0.3:5555',
  native-run:android:utils:adb:getDeviceProperty   'shell',
  native-run:android:utils:adb:getDeviceProperty   'getprop',
  native-run:android:utils:adb:getDeviceProperty   'dev.bootcomplete' ] +0ms
  native-run:android:utils:adb:waitForBoot Device 192.168.0.3:5555 is booted! +0ms
Installing platforms/android/app/build/outputs/apk/debug/app-debug.apk...
  native-run:android:utils:adb:installApk Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s',
  native-run:android:utils:adb:installApk   '192.168.0.3:5555',
  native-run:android:utils:adb:installApk   'install',
  native-run:android:utils:adb:installApk   '-r',
  native-run:android:utils:adb:installApk   '-t',
  native-run:android:utils:adb:installApk   'platforms/android/app/build/outputs/apk/debug/app-debug.apk' ] +0ms
Starting application activity com.holonic.mech/com.holonic.mech.MainActivity...
  native-run:android:utils:adb:startActivity Invoking adb: '/home/lucio/Android/Sdk/platform-tools/adb' [ '-s',
  native-run:android:utils:adb:startActivity   '192.168.0.3:5555',
  native-run:android:utils:adb:startActivity   'shell',
  native-run:android:utils:adb:startActivity   'am',
  native-run:android:utils:adb:startActivity   'start',
  native-run:android:utils:adb:startActivity   '-W',
  native-run:android:utils:adb:startActivity   '-n',
  native-run:android:utils:adb:startActivity   'com.holonic.mech/com.holonic.mech.MainActivity' ] +0ms
Run Successful
lucio@pop-os:~/holonfix/mechanicionic$ 

```

With the last one the app is installed in the phone, but it doesn't connect to livereload.

**Comment by luciojb** [comment]
Got it working only with this command:

`ionic cordova run android --address 0.0.0.0 --port 8100 --livereload --no-native-run`

**Comment by dwieeb** [comment]
Looks like we're running into this: https://stackoverflow.com/questions/51592477/adb-s-192-168-1-65555-error-more-than-one-device-emulator 😞 

Does adb not support port forwarding on devices connected over tcp/ip? I haven't been able to find anything saying it does or does not.

**Comment by nationdata-it** [comment]
thanks @luciojb you saved my day

**Comment by ZaLiTHkA** [comment]
Just to add my 2-cents' worth: I needed to run a current project in an older Android version (emulator), which was giving me a similar issue as that mentioned here.. I didn't have multiple targets available, only a single emulator already running, but adding `--host` (the new replacement for `--address`), `--port`, and `--no-native-run` allowed me to deploy and run my app in the older Android versions.

> Got it working only with this command:
> 
> `ionic cordova run android --address 0.0.0.0 --port 8100 --livereload --no-native-run`

**Comment by alitalaee** [comment]
I had the same issue and fixed 

**
Android device over tcpip:5555 error: more than one device/emulator

This Error caused you have more than one device when you run command  `adb devices`, you should close all devices and only open one...
**

FOR ANDROID 

### Enabling TCP Mode

1. Connect your device to your computer with USB to begin setup. Run `adb devices` to make sure the device is listed.

2. Switch ADB from USB to TCP mode.

```
adb tcpip 5555
```
3.Establish a connection from your computer to the device by using the device's IP on the shared LAN (device and computer need to be on the same Wi-Fi network). You can get the device's IP by going to Settings -> About phone -> Network -> IP address.
```
adb connect 192.168.0.xxx
```

4. Unplug the phone and run `adb devices` to ensure the connection was established (the device will now be listed as an IP).

Run ionic app now 
```
ionic cordova run android --address localhost --port 8100 --livereload 
```

This is Worked For me I hope It will help
