### ISSUE TITLE
[native-run] adb.exe: error: cannot bind listener: Operation not permitted

### ISSUE THREAD

**Issue by mightytyphoon** [ionic-team/native-run#39]
Hi,
This error occurs while using livereload command (-l flag), it seems that adb.exe refuses to bind to listener.
This could be related to the update made by google.

command used : ```ionic cordova emulate android -l```
Output :
```
D:\Work\benzaiten\mobile-app\benzaiten>ionic cordova emulate android --target=Nexus_5X_API_29 -l
> ng.cmd run app:ionic-cordova-serve --host=localhost --port=8100 --platform=android
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

> cordova.cmd build android --target Nexus_5X_API_29
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --target Nexus_5X_API_29 --connect --forward 8100:8100
[ng] Date: 2019-06-06T17:39:14.280Z
[ng] Hash: ad415a1f46486ce1f9fa
[ng] Time: 18198ms
[ng] chunk {common} common.js, common.js.map (common) 20.2 kB  [rendered]
[ng] chunk {cordova} cordova.js, cordova.js.map (cordova) 62.4 kB [entry] [rendered]
[ng] chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 285 kB [initial] [rendered]
[ng] chunk {home-home-module} home-home-module.js, home-home-module.js.map (home-home-module) 17.3 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 31.9 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 237 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.79 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 88 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.37 MB [initial] [rendered]
[INFO] ... and 173 additional chunks
[ng] i ｢wdm｣: Compiled successfully.
[native-run] Selected emulator emulator-5554
[native-run] Error: Command failed: C:\Users\laurent\AppData\Local\Android\Sdk\platform-tools/adb -s emulator-5554 reverse tcp:8100 tcp:8100
[native-run] adb.exe: error: cannot bind listener: Operation not permitted
[native-run]
[native-run]     at ChildProcess.exithandler (child_process.js:297:12)
[native-run]     at ChildProcess.emit (events.js:197:13)
[native-run]     at maybeClose (internal/child_process.js:984:16)
[native-run]     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by dwieeb** [comment]
@mightytyphoon Would you mind pasting the output of `native-run android --sdk-info`?

**Comment by ochikov** [comment]
I have the same error. When run the command `ionic cordova run android -l` without opened device in simulator, I get very old device with old Android version.
When opened device in simulator with Android 10, (Nexus 5X) i get the same error. The output of the command `native-run android --sdk-info` is as follows: 

```
API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  1
                      Google APIs Intel x86 Atom System Image  system-images;android-29;google_apis;x86  5


API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  8
                      Sources for Android 28  sources;android-28  1


API Level:            27
Packages:             Android SDK Platform 27  platforms;android-27  3
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-27;google_apis_playstore;x86  /.+/


API Level:            24
Packages:             Google Play Intel x86 Atom System Image  system-images;android-24;google_apis_playstore;x86  19
(!) Missing Packages: Android SDK Platform 24  platforms;android-24


API Level:            23
Packages:             Android SDK Platform 23  platforms;android-23  3
                      Sources for Android 23  sources;android-23  1


Tools:

Android Emulator  emulator  29.1.12
Android SDK Build-Tools 19.1  build-tools;19.1.0  19.1.0
Android SDK Build-Tools 20  build-tools;20.0.0  20.0.0
Android SDK Build-Tools 28.0.3  build-tools;28.0.3  28.0.3
Android SDK Build-Tools 29.0.1  build-tools;29.0.1  29.0.1
Android SDK Build-Tools 29.0.2  build-tools;29.0.2  29.0.2
Android SDK Platform-Tools  platform-tools  29.0.4
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1
```

**Comment by ochikov** [comment]
My solution is to run the following commands:
`adb kill-server`
`adb root`

Then again run the command: `ionic cordova run android -l` and the app is successfully started on later sdk version.
