### ISSUE TITLE
Error: There was an error installing app (at protocolClient.sendMessage )

### ISSUE THREAD

**Issue by pablomaurer** [ionic-team/native-run#67]
**Version:** 0.2.7 

**Description:** 

ionic cordova run ios failed (with real device connected)

**Command Output:**

```
[native-run] Error: There was an error installing app
[native-run]     at protocolClient.sendMessage (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/installation_proxy.js:59:24)
[native-run]     at LockdownProtocolReader.reader.readerFactory.create [as callback] (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/protocol.js:91:21)
[native-run]     at LockdownProtocolReader.onData (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/protocol/protocol.js:52:26)
[native-run]     at Socket.emit (events.js:189:13)
[native-run]     at addChunk (_stream_readable.js:284:12)
[native-run]     at readableAddChunk (_stream_readable.js:265:11)
[native-run]     at Socket.Readable.push (_stream_readable.js:220:10)
[native-run]     at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```

**Environment Info:**

```
Ionic:

   Ionic CLI                     : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 11 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.7 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.10.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001
```

**macOS version:**  10.14.5

**Comment by gravyplaya** [comment]
I get this error right now. Is there a way to fix it?

**Comment by michelepatrassi** [comment]
> I get this error right now. Is there a way to fix it?

@gravyplaya you need to go to xcode and register the device in the signing & capabilities tab (you need to do this the first time you connect a new device)

**Comment by jdnichollsc** [comment]
I was getting a warning:
`You currently don't have access to this membership resource. To resolve this issue, agree to the latest Program License Agreement in your developer account.`
This was fixed after navigate to `https://developer.apple.com/account`, accept the Agreement, and try again from Xcode, also registering the device from Signing & Capabilities 👍
