### ISSUE TITLE
Emulator won't start

### ISSUE THREAD

**Issue by ozergul** [ionic-team/native-run#74]
**Version:**

0.2.8

**Description:**

Hello
native-run doesn't see the emulator or dont create a new one. As I see DeviceList is empty. What's the problem? I am trying to solve for 2 days.

**Command Output:**

```
native-run ios --app platforms/ios/build/emulator/MyBookie.app --forward 8100:8100 --verbose
[native-run] 2019-08-14T10:22:13.062Z client:usbmuxd connectUsbmuxdSocket
[native-run] 2019-08-14T10:22:13.070Z client:usbmuxd getDevices
[native-run] 2019-08-14T10:22:13.076Z protocol:usbmux socket write: {"messageType":"ListDevices"}
[native-run] 2019-08-14T10:22:13.789Z protocol:usbmux Response: {"DeviceList":[]}
[native-run] 2019-08-14T10:22:13.791Z native-run Caught fatal error: TypeError: Cannot read property 'udid' of undefined
[native-run]     at Object.run (/usr/local/lib/node_modules/native-run/dist/ios/run.js:56:80)
[native-run]     at process._tickCallback (internal/process/next_tick.js:68:7)
[native-run] TypeError: Cannot read property 'udid' of undefined
[native-run]     at Object.run (/usr/local/lib/node_modules/native-run/dist/ios/run.js:56:80)
[native-run]     at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess native-run.

        native-run ios --app platforms/ios/build/emulator/MyBookie.app --forward 8100:81... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 5 functions +0ms
  ionic:lib:hooks Looking for ionic:serve:after npm script. +55s
  ionic:utils-process processExit: exiting (exit code: 1) +60ms
```

**Environment Info:**

```
Ionic:

   Ionic CLI                     : 5.2.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   ios-sim : 8.0.1
   NodeJS  : v10.16.2 (/usr/local/lib/node_modules/node/bin/node)
   npm     : 6.9.0
   OS      : macOS Mojave
   Xcode   : Xcode 10.0 Build version 10A255
```

macOS version: 10.14.2

Xcode version: 10.0 (10A255)

**Comment by MehtaAr25** [comment]
Facing the same issue.... any resolutions?

**Comment by sscots** [comment]
+1

**Comment by ademirfn** [comment]
+2

**Comment by WaldiirNeto** [comment]
+3

**Comment by roostaeian** [comment]
+4

**Comment by mmestica** [comment]
+5

**Comment by tlancina** [comment]
Anyone running in to this issue, could you please post the output of `xcrun simctl list --json`? Thanks!

**Comment by bhushankumarl** [comment]
@tlancina 
```
{
  "devicetypes" : [
    {
      "name" : "iPhone 4s",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-4s"
    },
    {
      "name" : "iPhone 5",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-5"
    },
    {
      "name" : "iPhone 5s",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"
    },
    {
      "name" : "iPhone 6",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6"
    },
    {
      "name" : "iPhone 6 Plus",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus"
    },
    {
      "name" : "iPhone 6s",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"
    },
    {
      "name" : "iPhone 6s Plus",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus"
    },
    {
      "name" : "iPhone 7",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-7"
    },
    {
      "name" : "iPhone 7 Plus",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus"
    },
    {
      "name" : "iPhone 8",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8"
    },
    {
      "name" : "iPhone 8 Plus",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus"
    },
    {
      "name" : "iPhone SE",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE"
    },
    {
      "name" : "iPhone X",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-X"
    },
    {
      "name" : "iPhone XR",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XR"
    },
    {
      "name" : "iPhone XS",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS"
    },
    {
      "name" : "iPhone XS Max",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max"
    },
    {
      "name" : "iPad 2",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-2"
    },
    {
      "name" : "iPad Retina",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Retina"
    },
    {
      "name" : "iPad Air",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air"
    },
    {
      "name" : "iPad Air 2",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air-2"
    },
    {
      "name" : "iPad (5th generation)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-"
    },
    {
      "name" : "iPad Pro (9.7-inch)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-"
    },
    {
      "name" : "iPad Pro (12.9-inch)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro"
    },
    {
      "name" : "iPad Pro (12.9-inch) (2nd generation)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-"
    },
    {
      "name" : "iPad Pro (10.5-inch)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-"
    },
    {
      "name" : "iPad (6th generation)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-"
    },
    {
      "name" : "Apple TV",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p"
    },
    {
      "name" : "Apple TV 4K",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K"
    },
    {
      "name" : "Apple TV 4K (at 1080p)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p"
    },
    {
      "name" : "Apple Watch - 38mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"
    },
    {
      "name" : "Apple Watch - 42mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"
    },
    {
      "name" : "Apple Watch Series 2 - 38mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm"
    },
    {
      "name" : "Apple Watch Series 2 - 42mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm"
    },
    {
      "name" : "Apple Watch Series 3 - 38mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm"
    },
    {
      "name" : "Apple Watch Series 3 - 42mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm"
    },
    {
      "name" : "Apple Watch Series 4 - 40mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm"
    },
    {
      "name" : "Apple Watch Series 4 - 44mm",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm"
    }
  ],
  "runtimes" : [
    {
      "buildversion" : "16A366",
      "availability" : "(available)",
      "name" : "iOS 12.0",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-12-0",
      "version" : "12.0"
    },
    {
      "buildversion" : "16J364",
      "availability" : "(available)",
      "name" : "tvOS 12.0",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.tvOS-12-0",
      "version" : "12.0"
    },
    {
      "buildversion" : "16R363",
      "availability" : "(available)",
      "name" : "watchOS 5.0",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.watchOS-5-0",
      "version" : "5.0"
    }
  ],
  "devices" : {
    "watchOS 5.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "B763EF6D-9011-4B77-A23F-397E418C7BEB"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "A5488347-1DD7-4F04-8C1E-3BA4426AE68D"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 3 - 38mm",
        "udid" : "83488E13-E45C-46CF-89CB-7EAC5FEF013D"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 3 - 42mm",
        "udid" : "DC1BB763-50A6-4647-A1BC-0F008EC7CB14"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "3D91F7CF-1E55-4F94-B528-1C4D8FAA474B"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "BFC6D3E7-4BC4-4CA2-9744-AF6A675EFFF2"
      }
    ],
    "iOS 12.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 5s",
        "udid" : "566A5DD9-3587-457E-9522-F311553DDFF7"
      },
      {
        "state" : "Booted",
        "availability" : "(available)",
        "name" : "iPhone 6",
        "udid" : "98918C31-05A6-4AFD-825C-D9BD802813FC"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6 Plus",
        "udid" : "8D63470D-46E7-4F4F-A708-D6E7437B338C"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6s",
        "udid" : "C27A9AB3-8B85-4B9F-853B-4B9243DA2D63"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 6s Plus",
        "udid" : "FE42C7F7-C6CD-4E12-8F6F-B85422C7D2EF"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 7",
        "udid" : "254561FA-4D8F-45F9-83BB-D6CA24233FBD"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 7 Plus",
        "udid" : "809DF8BA-8524-488D-A568-8246F0B9F2D5"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 8",
        "udid" : "2E1B6002-6930-4F2E-8BDC-A03E10539451"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone 8 Plus",
        "udid" : "F0318DCA-237F-4E8B-9727-5F04F0789E19"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone SE",
        "udid" : "5188E7F3-3FA5-4BE7-8B6A-06BF58138465"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone X",
        "udid" : "D1D1F6F7-22B9-495B-863B-673EB3D3A653"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone XR",
        "udid" : "C96B0FF8-9AD0-4303-83E6-A10474759599"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone XS",
        "udid" : "B9F20032-8D0F-4409-99FE-9EB5464BFF98"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPhone XS Max",
        "udid" : "B09CEA7A-A30D-4B4D-B253-29E7308EA7F6"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Air",
        "udid" : "CEA8B5B9-1250-49C1-9AEF-2FD3FEE888A2"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Air 2",
        "udid" : "6C0BC127-3DE2-4D4C-98B7-FFCDA30ED7A6"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad (5th generation)",
        "udid" : "5BFB811F-8B70-456C-B7CD-085A8E2CF032"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "A22FEA8B-1FEB-4CAA-A623-3EAEB8B00642"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (12.9-inch)",
        "udid" : "E10DC1D1-3D5C-416F-B354-0062435084BF"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "BF1C5A85-D769-4DDE-A4AC-FD084305AB20"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "64CBA480-281E-4237-9C3C-B57EAA00BDE5"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "iPad (6th generation)",
        "udid" : "6EF38A2B-8142-4A98-B677-DF8298446630"
      }
    ],
    "tvOS 12.0" : [
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple TV",
        "udid" : "C346C436-F314-45E5-8880-04F8489FC3EA"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple TV 4K",
        "udid" : "D57B14EB-56D0-4948-AE0A-D56C02A86DA0"
      },
      {
        "state" : "Shutdown",
        "availability" : "(available)",
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "9F791E76-5166-41CA-A93F-388024202548"
      }
    ]
  },
  "pairs" : {
    "094263AE-465B-404D-BFDD-DAE71AFD2718" : {
      "watch" : {
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "3D91F7CF-1E55-4F94-B528-1C4D8FAA474B",
        "state" : "Shutdown"
      },
      "phone" : {
        "name" : "iPhone XS",
        "udid" : "B9F20032-8D0F-4409-99FE-9EB5464BFF98",
        "state" : "Shutdown"
      },
      "state" : "(active, disconnected)"
    },
    "50B753A9-D1CE-4C32-B871-830266549FC0" : {
      "watch" : {
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "BFC6D3E7-4BC4-4CA2-9744-AF6A675EFFF2",
        "state" : "Shutdown"
      },
      "phone" : {
        "name" : "iPhone XS Max",
        "udid" : "B09CEA7A-A30D-4B4D-B253-29E7308EA7F6",
        "state" : "Shutdown"
      },
      "state" : "(active, disconnected)"
    }
  }
}
```
