### ISSUE TITLE
App name with UTF8 encoding in config.xml hangs forever

### ISSUE THREAD

**Issue by pipoa** [ionic-team/native-run#78]
**Version:**

0.2.8

**Description:**

App display name with UTF8 encoding(not ascii) in config.xml  hangs forever

[ config.xml ]
```
such as ...
<name>我的程式</name>
<name>私のプログラム</name>
<name>मेरा कार्यक्रम</name>
```
**Command Output:**

forever hangs, no error messages...
Instead, running WITHOUT native-run is ok

**Environment Info:**

Ionic:

   Ionic CLI                     : 5.2.8 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 27 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/avex/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

macOS version:
10.14.4

Xcode version:
10.2

**Comment by shifu-cyber** [comment]
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 79. Received 80
[native-run]     at boundsError (internal/buffer.js:49:9)
[native-run]     at writeU_Int8 (internal/buffer.js:558:5)
[native-run]     at Buffer.writeUInt8 (internal/buffer.js:565:10)
[native-run]     at toCString (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:150:9)
[native-run]     at AFCClient.openFile (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:50:9)
[native-run]     at AFCClient.uploadFile (/usr/local/lib/node_modules/native-run/node_modules/node-ioslib/dist/client/afc.js:69:24)
I ve the error smilar to yours.

**Comment by junbonglee** [comment]
Having same issue. It has been almost 4 months now since first error was reported. Is there any way to solve this?

**Comment by Bernix01** [comment]
2022 this is still a thing!

**Comment by Bernix01** [comment]
Fun fact if you end up here.
non alphanumeric characters in any file will cause this error. For example an image named `árbol.png`
