### ISSUE TITLE
iOS 13.2 gives Error: ImageMountFailed

### ISSUE THREAD

**Issue by sinan92** [ionic-team/native-run#86]
**Version:**

0.2.9

**Description:**

When I run the command: 

    ionic cordova run ios --livereload --address=0.0.0.0 --external --verbose --consolelogs

I get the error message: Error: ImageMountFailed

**Command Output:**

9,25,214,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,234]}}
[native-run] Error: ImageMountFailed
[native-run]     at LockdownProtocolReader.parseBody (/Volumes/www/relation-app/node_modules/node-ioslib/dist/protocol/lockdown.js:35:19)
[native-run]     at LockdownProtocolReader.onData (/Volumes/www/relation-app/node_modules/node-ioslib/dist/protocol/protocol.js:52:40)
[native-run]     at TLSSocket.emit (events.js:198:13)
[native-run]     at addChunk (_stream_readable.js:288:12)
[native-run]     at readableAddChunk (_stream_readable.js:269:11)
[native-run]     at TLSSocket.Readable.push (_stream_readable.js:224:10)
[native-run]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
[ERROR] An error occurred while running subprocess native-run.
        
        native-run ios --app "platforms/ios/build/device/Relation Portal.ipa" --device -... exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 5 functions +0ms
  ionic:lib:hooks Looking for ionic:serve:after npm script. +5m
  ionic:utils-process processExit: exiting (exit code: 1) +45ms

**Environment Info:**

Ionic:

   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 9 other plugins)

Utility:

   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.9 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.12.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a

Xcode version:
11

**Comment by sinan92** [comment]
While iOS 13.2 is released, they didn't release the newest version of XCode yet. I am installing it right now to see if that fixes the problem and I suspect it will. I will keep you updated.
