### ISSUE TITLE
ERR_NO_DEVICE: No hardware devices found.

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/native-run#93]
**Version:**

version: 0.2.9

**Description:**

won't find device and _when/if_ the device is found stops monitoring after 20 seconds.
1st issue currently faced is that it takes about 30 minutes of me trying to get the app to launch on my phone.

2nd(not sure if related to you guys): when viewing in chome://inspect quickly after viewing any console logs I get the pop up saying to `connect device to dev tools` and then I need to cancel close the running process and then try for about 30 minutes again to get it show on any android device. I am using an OnePlus 6 and a BQ Aquaris u2 lite, both have this issue.

**Command Output:**

**SDK Info:**
```
SDK Location:         /Users/c.francia/Library/Android/sdk
AVD Home:             /Users/c.francia/.android/avd

API Level:            29
Packages:             Android SDK Platform 29  platforms;android-29  3
                      Sources for Android 29  sources;android-29  1


API Level:            28
Packages:             Android SDK Platform 28  platforms;android-28  6
                      Sources for Android 28  sources;android-28  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-28;google_apis_playstore;x86  /.+/


API Level:            27
Packages:             Android SDK Platform 27  platforms;android-27  3
                      Sources for Android 27  sources;android-27  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-27;google_apis_playstore;x86  /.+/


API Level:            26
Packages:             Android SDK Platform 26  platforms;android-26  2
                      Sources for Android 26  sources;android-26  1
(!) Missing Packages: Google Play Intel x86 Atom System Image  system-images;android-26;google_apis_playstore;x86  /.+/


Tools:

Android Emulator  emulator  29.2.1
Android SDK Build-Tools 28.0.3  build-tools;28.0.3  28.0.3
Android SDK Build-Tools 29.0.2  build-tools;29.0.2  29.0.2
Android SDK Platform-Tools  platform-tools  29.0.4
Android SDK Tools  tools  26.1.1
SDK Patch Applier v4  patcher;v4  1
```

```
BUILD SUCCESSFUL in 12s
45 actionable tasks: 6 executed, 39 up-to-date
Command finished with error code 0: /Users/c.francia/Desktop/dicus/dicus/application/app/platforms/android/gradlew cdvBuildDebug,-b,/Users/c.francia/Desktop/dicus/dicus/application/app/platforms/android/build.gradle
Built the following apk(s):
	/Users/c.francia/Desktop/dicus/dicus/application/app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
> native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug.apk --device --verbose
[native-run] 2019-12-03T11:57:30.234Z native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME
[native-run] 2019-12-03T11:57:30.235Z native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT
[native-run] 2019-12-03T11:57:30.236Z native-run:android:utils:sdk:resolveSDKRoot Looking at following directories: [ '/Users/c.francia/Library/Android/sdk' ]
[native-run] 2019-12-03T11:57:30.240Z native-run:android:utils:sdk:resolveSDKRoot Using /Users/c.francia/Library/Android/sdk
[native-run] 2019-12-03T11:57:30.241Z native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME
[native-run] 2019-12-03T11:57:30.241Z native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android
[native-run] 2019-12-03T11:57:30.242Z native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /Users/c.francia/.android
[native-run] 2019-12-03T11:57:30.242Z native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME
[native-run] 2019-12-03T11:57:30.243Z native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd
[native-run] 2019-12-03T11:57:30.243Z native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /Users/c.francia/.android/avd
[native-run] 2019-12-03T11:57:30.244Z native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platform-tools/package.xml
[native-run] 2019-12-03T11:57:30.270Z native-run:android:utils:adb:getDevices Invoking adb: '/Users/c.francia/Library/Android/sdk/platform-tools/adb' [ 'devices', '-l' ]
[native-run] 2019-12-03T11:57:30.286Z native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ]
[native-run] 2019-12-03T11:57:30.286Z native-run:android:utils:adb:getDevices Found adb devices: []
[native-run] 2019-12-03T11:57:30.287Z native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: []
[native-run] 2019-12-03T11:57:30.288Z native-run Caught fatal error: RunException [Error]: No hardware devices found. Not attempting emulator because --device was specified.
[native-run]     at selectDevice (/Users/c.francia/Desktop/dicus/dicus/application/app/node_modules/native-run/dist/android/run.js:82:19)
[native-run]     at async Object.run (/Users/c.francia/Desktop/dicus/dicus/application/app/node_modules/native-run/dist/android/run.js:31:20)
[native-run]     at async Object.run (/Users/c.francia/Desktop/dicus/dicus/application/app/node_modules/native-run/dist/android/index.js:18:5)
[native-run]     at async Object.run (/Users/c.francia/Desktop/dicus/dicus/application/app/node_modules/native-run/dist/index.js:19:13) {
[native-run]   code: 'ERR_NO_DEVICE',
[native-run]   exitCode: 1,
[native-run]   data: undefined
[native-run] }
[native-run] ERR_NO_DEVICE: No hardware devices found. Not attempting emulator because --device was specified.
[ERROR] An error occurred while running subprocess native-run.

        native-run android --app platforms/android/app/build/outputs/apk/debug/app-debug... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 3 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +38ms
```

thanks for any help

**Comment by dwieeb** [comment]
@ctfrancia Please check to see if the latest release (0.3.0) solves this issue for you. If not, please run the following and post output:

```
native-run android --list --verbose
```

**Comment by ctfrancia** [comment]
sorry for the late comment, been a long week. I'll update and let you know at the end of the day the results, thanks.

**Comment by ctfrancia** [comment]
still the same issue:
results after `$ native-run android --list --verbose`
```
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT +7ms
  native-run:android:utils:sdk:resolveSDKRoot Looking at following directories: [ '/Users/c.francia/Library/Android/sdk' ] +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using /Users/c.francia/Library/Android/sdk +29ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /Users/c.francia/.android +1ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /Users/c.francia/.android/avd +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platform-tools/package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /Users/c.francia/Library/Android/sdk to discover SDK packages +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/Users/c.francia/Library/Android/sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [
  native-run:android:utils:adb:parseAdbDevices   'List of devices attached',
  native-run:android:utils:adb:parseAdbDevices   'UN045654               device usb:336805888X product:yamchalite model:Aquaris_U2_Lite device:yamchalite transport_id:315',
  native-run:android:utils:adb:parseAdbDevices   '',
  native-run:android:utils:adb:parseAdbDevices   ''
  native-run:android:utils:adb:parseAdbDevices ] +0ms
  native-run:android:utils:adb:getDeviceProperties Invoking adb: '/Users/c.francia/Library/Android/sdk/platform-tools/adb' [ '-s', 'UN045654', 'shell', 'getprop' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [
  native-run:android:utils:adb:getDevices   {
  native-run:android:utils:adb:getDevices     serial: 'UN045654',
  native-run:android:utils:adb:getDevices     state: 'device',
  native-run:android:utils:adb:getDevices     type: 'hardware',
  native-run:android:utils:adb:getDevices     connection: 'usb',
  native-run:android:utils:adb:getDevices     properties: {
  native-run:android:utils:adb:getDevices       usb: '336805888X',
  native-run:android:utils:adb:getDevices       product: 'yamchalite',
  native-run:android:utils:adb:getDevices       model: 'Aquaris_U2_Lite',
  native-run:android:utils:adb:getDevices       device: 'yamchalite',
  native-run:android:utils:adb:getDevices       transport_id: '315'
  native-run:android:utils:adb:getDevices     },
  native-run:android:utils:adb:getDevices     manufacturer: 'bq',
  native-run:android:utils:adb:getDevices     model: 'Aquaris U2 Lite',
  native-run:android:utils:adb:getDevices     product: 'yamchalite',
  native-run:android:utils:adb:getDevices     sdkVersion: '25'
  native-run:android:utils:adb:getDevices   }
  native-run:android:utils:adb:getDevices ] +115ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/build-tools/29.0.2/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-26/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-29/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-26/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-29/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '29',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-29', 'sources;android-29' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-28', 'sources;android-28' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '27',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-27', 'sources;android-27' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '26',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-26', 'sources;android-26' ]
  native-run:android:utils:sdk:api:getAPILevels   }
  native-run:android:utils:sdk:api:getAPILevels ] +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 29: Unsupported API level: 29 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 28: Unsatisfied packages within API 28: system-images;android-28;google_apis_playstore;x86 +1ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 27: Unsatisfied packages within API 27: system-images;android-27;google_apis_playstore;x86 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 26: Unsatisfied packages within API 26: system-images;android-26;google_apis_playstore;x86 +20ms

Errors (!):

  ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

Connected Devices:

  bq Aquaris U2 Lite (API 25) UN045654

Virtual Devices:

  No virtual devices found
```

**Comment by dwieeb** [comment]
It looks like you didn't update to 0.3.0, unless I missed something.

**Comment by ctfrancia** [comment]
that's strange, when I run
after doing `yarn global upgrade native-run` nothing happens. Let me look into this and see whats going on.

**Comment by ctfrancia** [comment]
I upgraded it to `0.3.0` however the issue persists:

```

  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_SDK_ROOT +1ms
  native-run:android:utils:sdk:resolveSDKRoot Looking at following directories: [ '/Users/c.francia/Library/Android/sdk' ] +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using /Users/c.francia/Library/Android/sdk +2ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android +1ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at /Users/c.francia/.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at /Users/c.francia/.android/avd +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platform-tools/package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking /Users/c.francia/Library/Android/sdk to discover SDK packages +0ms
  native-run:android:utils:adb:getDevices Invoking adb: '/Users/c.francia/Library/Android/sdk/platform-tools/adb' [ 'devices', '-l' ] +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [ 'List of devices attached', '', '' ] +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [] +18ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/emulator/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/tools/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/build-tools/28.0.3/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/build-tools/29.0.2/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/patcher/v4/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-26/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/platforms/android-29/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-26/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-27/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-28/package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing /Users/c.francia/Library/Android/sdk/sources/android-29/package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '29',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-29', 'sources;android-29' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '28',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-28', 'sources;android-28' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '27',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-27', 'sources;android-27' ]
  native-run:android:utils:sdk:api:getAPILevels   },
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '26',
  native-run:android:utils:sdk:api:getAPILevels     packages: [ 'platforms;android-26', 'sources;android-26' ]
  native-run:android:utils:sdk:api:getAPILevels   }
  native-run:android:utils:sdk:api:getAPILevels ] +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 29: Unsatisfied packages within API 29: system-images;android-29;google_apis_playstore;x86 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 28: Unsatisfied packages within API 28: system-images;android-28;google_apis_playstore;x86 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 27: Unsatisfied packages within API 27: system-images;android-27;google_apis_playstore;x86 +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 26: Unsatisfied packages within API 26: system-images;android-26;google_apis_playstore;x86 +0ms

Errors (!):

  ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
```

my device is plugged in.

**Comment by dwieeb** [comment]
There's a difference in your output now:

```diff
-  native-run:android:utils:adb:getDevices Found adb devices: [
-  native-run:android:utils:adb:getDevices   {
-  native-run:android:utils:adb:getDevices     serial: 'UN045654',
-  native-run:android:utils:adb:getDevices     state: 'device',
-  native-run:android:utils:adb:getDevices     type: 'hardware',
-  native-run:android:utils:adb:getDevices     connection: 'usb',
-  native-run:android:utils:adb:getDevices     properties: {
-  native-run:android:utils:adb:getDevices       usb: '336805888X',
-  native-run:android:utils:adb:getDevices       product: 'yamchalite',
-  native-run:android:utils:adb:getDevices       model: 'Aquaris_U2_Lite',
-  native-run:android:utils:adb:getDevices       device: 'yamchalite',
-  native-run:android:utils:adb:getDevices       transport_id: '315'
-  native-run:android:utils:adb:getDevices     },
-  native-run:android:utils:adb:getDevices     manufacturer: 'bq',
-  native-run:android:utils:adb:getDevices     model: 'Aquaris U2 Lite',
-  native-run:android:utils:adb:getDevices     product: 'yamchalite',
-  native-run:android:utils:adb:getDevices     sdkVersion: '25'
-  native-run:android:utils:adb:getDevices   }
-  native-run:android:utils:adb:getDevices ] +115ms
+  native-run:android:utils:adb:getDevices Found adb devices: [] +18ms
```

My guess is adb is being finicky as usual. Try unplugging & plugging in your device.

**Comment by ctfrancia** [comment]
yea, so, it is being very finicky. What I have noticed is that it depends frequently on the cord used to plug the android device into the computer with the USB cable. If it's a good quality cable then it tends to pick it up easier (though there is still wrestling required) and if it is a bad/cheap cable then severe frustration ensues. Strange it's this finicky. Thanks
